### PR TITLE
Update the react devtools backend to version 4.17.0

### PR DESCRIPTION
**Pull request by hbenl**
The react devtools frontend will be updated to 4.17.0 with RecordReplay/devtools#3323 . The new frontend is compatible with the old backend, but we should update the backend to the same version as the frontend anyway.
Note that I couldn't test this PR yet.

### CODE REVIEW

**Comment by hbenl** [comment]
@loganfsmyth Could you test this for me?

**Comment by loganfsmyth** [comment]
Alright here's what I got when I tried:

1. Upon opening devtools and clicking a component, I got
Screen Shot 2021-08-30 at 7 52 02 PM
this does eventually just go away, I'm not sure if it was because I clicked on it or what.

2. I also got this error
Screen Shot 2021-08-30 at 7 50 31 PM
The "Report this issue" notification seems like something we'd want to get rid of. I don't know about the error itself.

Here's a recording of me replaying my local backend since I thought it might be helpful to dig into: https://app.replay.io/recording/5a9e4a40-5162-4342-9819-46394f1c640b

**Comment by hbenl** [comment]
- the popup about the backend version appears because when the ReactDevTools frontend asks for the version of the ReactDevTools backend, the Replay backend takes some time to reply (I have added comments to the recording showing this). The ReactDevTools frontend contains a timeout that shows the popup if no reply for the backend version request is received for a couple of seconds (old versions of ReactDevTools don't know about the protocol messages asking for a version, so no reply usually means old backend). I think the error message about the backend version should simply be disabled since it doesn't make sense in the Replay context (the oldest backend version that we integrated already knew the protocol messages for getting the backend version)
- the "Could not inspect element" error seems to be an issue with ReactDevTools itself - I've seen it showing up sporadically in the ReactDevTools browser extension as well. We should create an issue in the React repo with STRs (see also https://github.com/facebook/react/issues?q=is%3Aissue+%22Could+not+inspect+element%22)

I think both issues are unrelated to this PR itself.

**Comment by ryanjduffy** [comment]
@hbenl + @loganfsmyth - What are the next steps on this?

**Comment by hbenl** [comment]
@loganfsmyth I'd like to merge this - do you approve?

**Review by loganfsmyth — APPROVED** [review]

**Comment by jasonLaster** [comment]
merging since we're all in agreement :)

**Pull request merged**
