### PR TITLE
Disable precaching code added in #461.

### PR DESCRIPTION
**Pull request by kannanvijayan**
To investigate crashiness probably introduced by patch for #461.

### CODE REVIEW

**Review by bhackett1024 — COMMENTED** [review]
Can we make this entire function return null, like it did before the precaching changes?

**Comment by bhackett1024** [comment]
It also seems better if we use a preference to enable this code, to make it easier to test with/without this logic.

**Comment by kannanvijayan** [comment]
I'll do that when I re-enable it.

**Comment by kannanvijayan** [comment]
> I'll do that when I re-enable it.

Actually I'll do that now.  I can't test effectively on the local machine because this happens sporadically and I can't make numerous recordings.  Testing against cloud infra is better.

**Pull request merged**
