### PR TITLE
Fix painting

### PR DESCRIPTION
**Pull request by bhackett1024**

### CODE REVIEW

**Review by kannanvijayan — APPROVED** [review]
IIUC, the fix is just the one-liner in AsyncPanZoomEnabled, and the rest of it is diagnostic support?

**Comment by bhackett1024** [comment]
> IIUC, the fix is just the one-liner in AsyncPanZoomEnabled, and the rest of it is diagnostic support?

Yeah, the actual fix is the first one line patch.

**Comment by kannanvijayan** [comment]
https://github.com/RecordReplay/backend/issues/1852 in backend is likely related to this as well.

APZ was mentioned when we discussed it initially.  I interpreted what you said then as confirming that APZ was already disabled on replay.  Does this mean that it was disabled in the replaying image but not the recording image?

**Comment by bhackett1024** [comment]
APZ was supposed to be disabled when viewing recording/replaying tabs --- this requires disabling it on the parent side because that is where most of the logic runs (though there is some cooperation with the content process).  This used to be the case, but at some point (probably when merging from upstream) this regressed and APZ was in use both when recording and replaying.

**Pull request merged**
