### PR TITLE
Make VisibleFrames in PresShell a replay-stable HashSet.

### LINKED ISSUE #830: Make `VisibleFrames` a stable hash-table
Should fix the RasterImage::LookupFrame mismatch issue.  See comment here (and following response):

https://github.com/RecordReplay/backend/issues/4719#issuecomment-1110122946

### PR DESCRIPTION
**Pull request by kannanvijayan**

### CODE REVIEW

**Comment by kannanvijayan** [comment]
I'm still wrangling around trying to get this to compile because of C++ dependency and include-order/namespace visibility.  The main purpose of the patch is to try to use stable integers to hash the pointers to nsIFrame instead of the raw pointer values.

**Comment by bhackett1024** [comment]
This looks like a good step to try, but because nsTHashSet uses a PLDHashTable internally, and those are already supposed to have stable iteration when replaying (and indeed do, for all the other types of these tables), it's hard to be sure if this will fix the problem we're seeing.

It would be better to put the hashtable definitions in one of the xpcom hashtable headers, which should make the build problems a lot easier to resolve.

**Comment by kannanvijayan** [comment]
> This looks like a good step to try, but because nsTHashSet uses a PLDHashTable internally, and those are already supposed to have stable iteration when replaying (and indeed do, for all the other types of these tables), it's hard to be sure if this will fix the problem we're seeing.

The other types of tables seem to be keyed on values that would be consistent between recording and replay.  The key values themselves may be diverging here, which is why I wanted to convert the pointers to a reasonable stand-in that would be consistent between recording and replayed.

> It would be better to put the hashtable definitions in one of the xpcom hashtable headers, which should make the build problems a lot easier to resolve.

I'll try this.

**Comment by kannanvijayan** [comment]
Well, none of the shortcuts I tried to reduce the surface area of this worked.  So now there's a surrogate "ReplayStable" variant of a bunch of hash-set things defined alongside the original things.  This builds now.  If it passes tests we should ship it and see if it eliminates the RasterImage crashes.

**Comment by kannanvijayan** [comment]
Moved the PR over to https://github.com/RecordReplay/gecko-dev/pull/845 which I could run tests on better.

**Pull request closed without merging**
