### PR TITLE
More assertions around MaybePokeCC and GetIdlePeriodHint

### PR DESCRIPTION
**Pull request by kannanvijayan**

### CODE REVIEW

**Review by bhackett1024 — CHANGES_REQUESTED** [review]
This feels heavyweight and not the right approach to the assert in the issue to me.  Have we ruled out differences in behavior in XPCJSContext::AfterProcessTask or nsJSContext::MaybePokeCC?  These functions should have assertions at entry / exit points so we can tell whether they are called at consistent points but are behaving differently.

**Comment by kannanvijayan** [comment]
> This feels heavyweight and not the right approach to the assert in the issue to me. Have we ruled out differences in behavior in XPCJSContext::AfterProcessTask or nsJSContext::MaybePokeCC? These functions should have assertions at entry / exit points so we can tell whether they are called at consistent points but are behaving differently.

I thought about this, and this felt like a better way to reveal information about what's going wrong.  My supposition here is that the task itself is different.  The MaybePokeCC and other logic is a red herring.  Reading the logic of the flow of code, and reasoning about the recorded stack vs replayed stack between this and other stack traces for crashes in this bucket.

Here is the mismatch example that dominates the crashes bucketed under this:

```json
{
  "telemetry.data.crashReport.processNonFatal.recordedStack": [
    "mozilla::TimeStamp::Now(bool)+9",
    "nsJSContext::MaybePokeCC()+16",
    "XPCJSContext::AfterProcessTask(unsigned.int)+1216",
    "nsThread::ProcessNextEvent(bool,.bool*)+1821",
    "NS_ProcessNextEvent(nsIThread*,.bool)+73",
    "mozilla::dom::ContentChild::ProvideWindowCommon(mozilla::dom::BrowserChild*,.nsIOpenWindowInfo*,.unsigned.i
nt,.bool,.bool,.nsIURI*,.nsTSubstring<char16_t>.const&,.nsTSubstring<char>.const&,.bool,.bool,.nsDocShellLoadSta
te*,.bool*,.mozilla::dom::BrowsingContext**)+3126",
    "mozilla::dom::BrowserChild::ProvideWindow(nsIOpenWindowInfo*,.unsigned.int,.bool,.bool,.nsIURI*,.nsTSubstri
ng<char16_t>.const&,.nsTSubstring<char>.const&,.bool,.bool,.nsDocShellLoadState*,.bool*,.mozilla::dom::BrowsingC
ontext**)+412",
    "nsWindowWatcher::OpenWindowInternal(mozIDOMWindowProxy*,.nsTSubstring<char>.const&,.nsTSubstring<char>.cons
t&,.nsTSubstring<char>.const&,.bool,.bool,.bool,.nsIArray*,.bool,.bool,.bool,.nsPIWindowWatcher::PrintKind,.nsDocShellLoadState*,.mozilla::dom::BrowsingContext**)+2593"
  ],
  "telemetry.data.crashReport.processNonFatal.replayedStack": [
    "mozilla::TimeStamp::Now(bool)+9",
    "mozilla::MainThreadIdlePeriod::GetIdlePeriodHint(mozilla::TimeStamp*)+41",
    "mozilla::IdlePeriodState::GetLocalIdleDeadline(bool&,.mozilla::detail::BaseAutoUnlock<mozilla::Mutex&>.const&)+130",
    "mozilla::IdlePeriodState::GetIdleDeadlineInternal(bool,.mozilla::detail::BaseAutoUnlock<mozilla::Mutex&>.const&)+46",
    "mozilla::TaskController::ExecuteNextTaskOnlyMainThreadInternal(mozilla::detail::BaseAutoLock<mozilla::Mutex&>.const&)+569",
    "mozilla::TaskController::ProcessPendingMTTask(bool)+57",
    "mozilla::detail::RunnableFunction<mozilla::TaskController::InitializeInternal()::$_1>::Run()+21",
    "nsThread::ProcessNextEvent(bool,.bool*)+1102"
  ],
}
```

Here the recorded stack is in AfterProcessTask, and the replaying stack is inside some runnable being processed.

We already have an assertion in `ProcessNextEvent` that guards the after-process-task.  Looking at the impl for that reveals that the MaybePokeCC is _always_ called within `AfterProcessTask` - there are no early returns.

I honestly think the CC poke is a red herring here.  It's only serving to provide the source of the `clock_gettime` recorded call that happens to interfere with any other source of `clock_gettime` due to event misordering.

**Comment by kannanvijayan** [comment]
Also, what's the concern about this being too heavyweight?  is the event dispatching code run too often for these asserts to be palatable?

**Comment by bhackett1024** [comment]
I was mostly concerned about the added code for do_QueryInterface, and also how the new assertions are only tangentially related to the actual mismatch being observed.

I agree that looking more closely at XPCJSContext::AfterProcessTask and nsJSContext::MaybePokeCC that TimeStamp::Now() will always be called when the former is invoked.  With the mismatch above that still leaves the possibility that TaskController::ProcessPendingMTTask() is being called at consistent points but that it behaves differently when called.

Also, I've found it's best to convert RecordedCallStackMismatches like this into regular LinkerMismatches by adding assertions, in this case before the TimeStamp::Now() calls in MainThreadIdlePeriod::GetIdlePeriodHint and nsJSContext::MaybePokeCC.  Once this is a LinkerMismatch then a full stack will be available when replaying, which is more helpful, and further assertions should be added that narrow things down to the root problem.  i.e. before adding assertions to nsThread::ProcessNextEvent we need to confirm that the different behavior is within this function and not somewhere else in the two stacks where the mismatch occurred.

**Comment by kannanvijayan** [comment]
I'm concerned that adding those asserts would only tell us more of what the current stack traces are telling us: different tasks are getting scheduled.  The only thing a longer stack is going to tell us is that once again, we're ending up in nsThread scheduling and then diverging somehow.

I can add the other asserts you're asking for, but I _really_ want to rule out the task names.  The nsINamed usage should eliminate or confirm the different-tasks hypothesis which is the strongest hypothesis currently IMHO.

Can we do both?

**Comment by bhackett1024** [comment]
> I'm concerned that adding those asserts would only tell us more of what the current stack traces are telling us: different tasks are getting scheduled. The only thing a longer stack is going to tell us is that once again, we're ending up in nsThread scheduling and then diverging somehow.

The current stack traces are not telling us that different tasks are getting scheduled.  They are also consistent with the same tasks getting scheduled, but the TaskController::ProcessPendingMTTask runnable behaving differently when recording vs. replaying.

It's important when adding assertions to think about the available information from the mismatch and what would help to further narrow down the possible source of the mismatched behavior.  In this case all we know is that calls to TimeStamp::Now() from nsJSContext::MaybePokeCC and MainThreadIdlePeriod::GetIdlePeriodHint are happening differently.

If we add an assertion at these TimeStamp::Now() calls and also at the beginning/end of TaskController::ProcessPendingMTTask(), then one of two possible things can happen:

1. We get a mismatch between the end of TaskController::ProcessPendingMTTask and the TimeStamp::Now call in MainThreadIdlePeriod::GetIdlePeriodHint.  This would indicate that there is different behavior within TaskController::ProcessPendingMTTask.
2. We get a mismatch between the start of TaskController::ProcessPendingMTTask and some other assertion (the MaybePokeCC one or something else).  This would indicate that different tasks are getting scheduled.

Once we've narrowed things down to one of these possibilities we'll be in a much better place to decide what new assertions are needed to get closer to the source of the problem.

**Comment by kannanvijayan** [comment]
I get your point, and I'll abide by the suggested approach - patch forthcoming soon.

But for the record I'll emphasize that given the length of the iteration loop on these things it's worthwhile for us to validate as many hypothesis as possible in one iteration.

Also, I meant to refer to the "nsThread event/runnable", not the TaskController task in the prior comment.

**Review by bhackett1024 — APPROVED** [review]
Thanks!  In general I agree that we should test additional hypotheses, but adding new QueryInterface and associated calls could have performance implications and I think we should only do such things when we've narrowed things down enough that we know it will help shed light on what is going on.

**Pull request merged**
